#!/bin/bash

echo "Triger received. Deploying..."
cd /opt/identiform
git --git-dir=/opt/identiform.git --work-tree=/opt/identiform checkout master -f

echo 'Installing'
npm install

echo 'Building...'
PORT=$PORT npm run build

echo 'Starting server.' 
pm2 reload identiform
PORT=3063 pm2 start ./index.js --name identiform

pm2 reload identiform_api
API_PORT=3086 pm2 start ./apiStart.js --name identiform_api
